### ISSUE TITLE
Trailing whitespace on provider_id

### ISSUE THREAD

**Issue by webb-ben** [internetofwater/ref_dams#13]
The provider_ids `SC00035`, `NJ00001` and `NJ00002` seem to have duplicate provider_ids with trailing whitespace. This results in duplication of these rows, breaking pygeoapi queries (thanks @cheginit for flagging).

![image](https://user-images.githubusercontent.com/40066515/230927024-02ad12b6-7d29-4f8c-8c5c-8cec91a2aa68.png)

Deleting the rows where `id=NULL` fixes pygeoapi queries. It seems that the rows are meant to be joined because the rows with a trailing space have a value in `subjectOf` but null `nhdpv2_comid`, and those without have a value for `nhdpv2_comid` but null `subjectOf`. Not sure where this is happening...

@dblodgett-usgs @ksonda

**Comment by dblodgett-usgs** [comment]
Thanks for flagging this -- I did not strip white space from the IDs because... why would IDs have white space? silly me... 

I will see about getting the duplicates removed.

**Comment by dblodgett-usgs** [comment]
OK -- I've fixed the issue. Catch is that I think I should leave the duplicate reference dam in place and plan to mark some duplicates like this as superseded in the future. Does that seem OK?

**Comment by dblodgett-usgs** [comment]
The file on hydroshare is updated... @webb-ben can you help me get it up there? The documentation here: https://github.com/internetofwater/geoconnex.us/tree/master/pygeoapi#contributing-new-content seems to be out of date?

**Comment by ksonda** [comment]
Ugh yeah. We forgot to update this. We're going through something with a massive reference feature set (census blocks) that can't be in hydroshare) so we need a pointer system. A stopgap would be to have a comment in the pygeoapi config that accomplishes the same thing as the "updated "
Comment in the dockerfile which would trigger the rebuild.

**Comment by ksonda** [comment]
triggered via https://github.com/internetofwater/geoconnex.us/commit/86d2043ae7d116f2fed9f236932e2adc66cfa134

**Comment by ksonda** [comment]
appears to resolve @cheginit issue 

```
curl --location --request POST 'https://reference.geoconnex.us/collections/dams/items?f=json&limit=12000&sortby=uri&filter-lang=cql-json&skipGeometry=false' \
--header "Content-Type: application/query-cql-json" \
--data-raw '{"within": [{"property": "geom"}, {"type": "Polygon", "coordinates": [[[-71.7898206, 36.6695658], [-71.7898206, 44.1530473], [-80.5409921, 44.1530473], [-80.5409921, 36.6695658], [-71.7898206, 36.6695658]]]}]}'
