### ISSUE TITLE
NID subjectOf URLs changed

### ISSUE THREAD

**Issue by ksonda** [internetofwater/ref_dams#14]
Pattern moved from https://nid.usace.army.mil/#/dams/system/OH03148/summary 

to 

https://nid.sec.usace.army.mil/#/dams/system/OH03148/summary 

Consider minting USACE NID PIDs so link maintenance can happen at geoconnex.us instead of the geopackage?

**Comment by dblodgett-usgs** [comment]
+1 You don't have someone who could tackle this, do you? I can try to bang it out if not.

**Comment by ksonda** [comment]
If you just show me where the lines of code is I can change it

**Comment by dblodgett-usgs** [comment]
Looks like it's here: https://github.com/internetofwater/ref_dams/blob/main/R/dam_locations.R#L141

**Comment by dblodgett-usgs** [comment]
Am getting this run with the new pattern now.
