### ISSUE TITLE
Incorporate hydrologic locations from NAWQA source and automated linking.

### ISSUE THREAD

**Issue by dblodgett-usgs** [internetofwater/ref_dams#18]
Just tracking that this work was done. Previously, establishing the network location of dams was not attempted. 

Their is a lot of complexity in what information is available and the relatively low quality of spatial information about dams. 

Need to figure out a way to get some or most gages on the network given that information that we do have. This issue can be closed once all dams that can have a location estimated for them have one and how it was created is documented.

**Comment by ksonda** [comment]
may want to cross-check with aquaticbarriers.org? They seem to be indexing to nhdplusHR

**Comment by dblodgett-usgs** [comment]
Not going to have time in this round of work. But there are probably a number of sources we should cross reference with.

**Comment by dblodgett-usgs** [comment]
I've decided to add a index type categorization that is terse but descriptive. Will write up a fuller description of each category here. 

1. nawqa_on_network_da_match
2. nawqa_off_network_da_mismatch
3. automatic_network_closest_flowline_no_da_check
4. automatic_network_closest_drainage_area

**Comment by ksonda** [comment]
Is there something in hy_features they these types match to?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dblodgett-usgs** [comment]
There may be something about on network vs off network to express... I'll have to think on that. The confidence of the match isn't something HY_Features would say anything about though.

**Comment by dblodgett-usgs** [comment]
https://github.com/internetofwater/ref_dams/releases/tag/0.1
