### ISSUE TITLE
Incorporating modern NID data into the registry.

### ISSUE THREAD

**Issue by dblodgett-usgs** [internetofwater/ref_dams#3]
The registry was initialized with a National Water Quality Assessment (NAWQA) dataset that is derived from extensive QC of on-network dams. It is far from perfect, but it represents the best national collection I was able to identify as a starting place. It has all dams in NID from a 2013 snapshot and a 2018 snapshot. As such, it has some issues related to #2 and there are many dams that, in the latest NID, have been moved. 

A basic analysis shows: 
![image](https://user-images.githubusercontent.com/1492803/169536890-541fe01e-4288-407d-8d44-e91d66305992.png)

3% with a distance greater than 1km feels reasonable.

Going down to a 100m distance, we have 28% that are more than 100m of each other.

Spot checks reveal that:
1) The unqualified NIDID identifiers are quite robust but not perfect.
2) In some cases, the modern NID has been updated such that those locations are more accurate but in other cases, the NAWQA locations are more accurate.

Here's my strategy for conflating the newest NID with the data used to initialize the registry:
- anything that's within 500m, we use the location from NAWQA as it will be closer to the NHDPlus (they moved things to flowlines).
- anything that's > 500m apart and on a river with drainage area > 100 sqkm we use the NAWQA location as they prioritized hydrologic location of major dams.
- anything that's > 500m apart and has unknown drainage area from NID or is < 100 sqkm we use the modern NID location.
- run a complete distance matrix, any that are within ~200m of each other and have different ids, I'll drop the NAWQA dataset feature at that location in favor of the location from the modern NID.

**Comment by dwief-usgs** [comment]
Thanks for getting this started.  I think the above strategy provides for a good starting point.  Nothing will be perfect given current datasets but getting the registry going sooner than later will keep issues from compounding.

**Comment by dblodgett-usgs** [comment]
Just leaving some breadcrumbs here...

![image](https://user-images.githubusercontent.com/1492803/169561450-401b9ab1-c40b-4b23-95b8-0c0b1557eed4.png)

This gives me all the information I have from the NAWQA dataset that can be compared to the modern NID. I can implement the logic outlined above with this.

**Comment by mikejohnson51** [comment]
Thanks for getting this started.  I agree location is secondary except that it is what allows you to get onto the network. OpenStreetMap is by far the best source for location and was easy (but compute intesinsive) to conflate with the 2019 NID snapshot. I played a bit with the NAQWA data that @dwief-usgs shared and didn’t find it added much to the OSM/NID mix when only using its location (it was of tremendous value for validation though! - along with FEMA FIM datasets). The thing with the OSM conflation is I needed a 2500 m buffer to get a lot of the NID dams closer to where they “should” be.

The strategy you online is very simular to what I did - just with a different “truth” dataset. However location/GNIS|river name were the conflators since the NID_id is not in the OSM dataset.

Also @dblodgett-usgs I am sure you found this but just in case: 

``` r
read.csv('https://nid.usace.army.mil/api/nation/csv', skip = 1)[1:5 ,1:5]
#>                                            Dam.Name            Other.Names
#> 1                               Aichi Forge Usa Dam   Aichi Forge Usa Lake
#> 2                                         Dod Usa 2                       
#> 3                                         Dod Usa 4                       
#> 4                            Oxy Usa Retention Pond                       
#> 5 Exxonmobil Coal Usa/Mine 2/Recirculation Lake Dam Make-Up Water Lake Dam
#>                                      Former.Names  NID.ID Other.Structure.ID
#> 1                                                 KY00728                   
#> 2                                         Dod Usa OK20994                   
#> 3                                         Dod Usa OK20998                   
#> 4                                                 ND01160                   
#> 5 Monterey  Coal Co/Mine 2/Recirculation Lake Dam IL50526
```

<sup>Created on 2022-05-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by dblodgett-usgs** [comment]
I've implemented all the checks above and included a "feature_data_source" attribute in the new data pointing to the NAWQA data release or the NID downloads page as appropriate. The IDs in the registry have no changed -- but the representations should be as clean as we can make them for now.

**Comment by dblodgett-usgs** [comment]
So we now have some like this: 
![image](https://user-images.githubusercontent.com/1492803/169630223-82e374f2-0665-4598-a576-55be6ae2501b.png)

That will not have a subjectOf at this point because they are not in the NID but are referenced in the NAWQA dataset.

Some like this: 

![image](https://user-images.githubusercontent.com/1492803/169630238-0b7173a9-67ac-40ae-b788-a2d562945186.png)

That have a NULL COMID because they are only present in the NID or for one of the criteria above, the NAWQA feature data was not used.

And ones like this: 

![image](https://user-images.githubusercontent.com/1492803/169630264-5207a1a3-7a42-48d3-af80-00fadd5a68b6.png)

Where we have decided to use the NAWQA data and they are also present in the NID. 

One thing to consider -- I do have drainage area estimates for many of these dams. Some are estimates from the NID, others are from NAWQA. I'm a little hesitant to add them as I have no way to document their source of quality, but maybe it would be worth adding them (and multiple estimates where estimates exist?)
